# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('product_type', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
